[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Saurav Singh"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^2.0.1"
Flask-SQLAlchemy = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
