openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /todos:
    get:
      summary: List all todos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Add a todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Bad request
    /{todo_id}:
      parameters:
        - in: path
          name: todo_id
          required: true
          schema:
            type: integer
            format: int64
      get:
        summary: Get a todo
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Todo'
          '404':
            description: Not found
      put:
        summary: Update a todo
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  done:
                    type: boolean
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Todo'
          '400':
            description: Bad request
          '404':
            description: Not found
      delete:
        summary: Delete a todo
        responses:
          '200':
            description: OK
          '404':
            description: Not found
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        task:
          type: string
        done:
          type: boolean
